language: python
sudo: false
jobs:
  include:
    - name: "Python 3.6 on Linux"
      python: '3.6'
    - name: "Python 3.7 on Linux"
      python: '3.7'
    - name: "Python 3.8 on Linux"
      python: '3.8'
    - name: "Python 3.8.0 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
install:
  - pip install codecov
  - pip install pytest-cov
script: coverage run -m pytest whatprovides/tests.py
after_success:
  - codecov
